parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony_test
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 10e1015966381f13a28108abd8bcd1ba510
    database_path: null
